// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAanL3nwW_Raimt46Sp2HrS0Nj6392bcN4',
    appId: '1:347294687654:web:ab518bef953c01de28ef67',
    messagingSenderId: '347294687654',
    projectId: 'kisan-mitra-2156f',
    authDomain: 'kisan-mitra-2156f.firebaseapp.com',
    storageBucket: 'kisan-mitra-2156f.firebasestorage.app',
    measurementId: 'G-J4BY2D1MTE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUzHhgK_uIOq2-PixbwpuHnIiaukZgz3g',
    appId: '1:347294687654:android:3cbc9dd3cf0259f428ef67',
    messagingSenderId: '347294687654',
    projectId: 'kisan-mitra-2156f',
    storageBucket: 'kisan-mitra-2156f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC0kEUcP7pNzklf4hpXyXAk8WuFm4vXFo',
    appId: '1:347294687654:ios:43126b224491641d28ef67',
    messagingSenderId: '347294687654',
    projectId: 'kisan-mitra-2156f',
    storageBucket: 'kisan-mitra-2156f.firebasestorage.app',
    iosBundleId: 'com.example.smartFarmerApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDC0kEUcP7pNzklf4hpXyXAk8WuFm4vXFo',
    appId: '1:347294687654:ios:43126b224491641d28ef67',
    messagingSenderId: '347294687654',
    projectId: 'kisan-mitra-2156f',
    storageBucket: 'kisan-mitra-2156f.firebasestorage.app',
    iosBundleId: 'com.example.smartFarmerApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAanL3nwW_Raimt46Sp2HrS0Nj6392bcN4',
    appId: '1:347294687654:web:901d49152d83ff5b28ef67',
    messagingSenderId: '347294687654',
    projectId: 'kisan-mitra-2156f',
    authDomain: 'kisan-mitra-2156f.firebaseapp.com',
    storageBucket: 'kisan-mitra-2156f.firebasestorage.app',
    measurementId: 'G-07BEXJ4L6X',
  );
}
